// Generated by CoffeeScript 1.10.0
(function() {
  var graph, i, jref, json, k, len, name, node, nodes, o, ref, s, space, undirender;

  undirender = require('undirender');

  jref = require('json-ref-lite');

  graph = [];

  json = require(__dirname + '/graph.coffee');

  json = jref.resolve(json);

  for (name in json) {
    node = json[name];
    json[name].name = name;
  }

  for (k in json) {
    node = json[k];
    if (node.output != null) {
      ref = node.output;
      for (i = 0, len = ref.length; i < len; i++) {
        o = ref[i];
        graph.push([node.name, o.name]);
      }
    }
  }

  nodes = graph.length;

  space = 2;

  s = undirender(nodes * space, parseInt((nodes / 2) * space), graph);

  console.log(s);

}).call(this);
