// Generated by CoffeeScript 1.9.3
(function() {
  var jflow, json, path, process;

  jflow = require('jsonflow');

  path = [];

  json = {
    a: {
      output: [
        {
          "$ref": "#/b"
        }
      ]
    },
    b: {
      output: [
        {
          "$ref": "#/a"
        }
      ]
    },
    c: {
      output: [
        {
          "$ref": "#/a"
        }
      ]
    }
  };

  process = {};

  process.increment = function(me, data, next) {
    if (data.arr == null) {
      data.arr = [];
    }
    data.arr.push(new Date());
    return next(me, data);
  };

  process.a = process.b = process.increment;

  jflow.filters.custom.debug = function(node, data) {
    var obj;
    obj = {};
    obj[node.name] = data;
    return console.log(JSON.stringify(obj, null, 2));
  };

  jflow.filters.global.rememberpath = function(node, data) {
    return path.push(node.name);
  };

  jflow.run(json, {
    foo: "bar"
  }, {
    root: 'b',
    process: process
  });

  console.log("path: " + path.join('->'));

}).call(this);
