// Generated by CoffeeScript 1.9.3
(function() {
  var a, b, c, graph, jg;

  jg = require('jsongraph');

  jg.opts.verbose = 2;

  graph = jg.init({
    graph: {}
  });

  a = graph.set("a");

  b = graph.set("b");

  c = graph.set("c");

  graph.link(a, b);

  graph.link("b", "c");

  graph.dump();

  graph.run('a', {
    foo: "bar"
  }, function(me, data, next) {
    if (me.name === 'b') {
      data.b = true;
    }
    return next(me, data);
  });

}).call(this);
