// Generated by CoffeeScript 1.10.0
(function() {
  var jflow, json, process;

  jflow = require('json-dataflow');

  json = {
    a: {
      output: [
        {
          "$ref": "#/b"
        }
      ]
    },
    b: {
      output: [
        {
          "$ref": "#/a"
        }
      ]
    },
    c: {
      output: [
        {
          "$ref": "#/a"
        }
      ]
    },
    d: {
      output: [
        {
          "$ref": "#/c"
        }
      ]
    }
  };

  process = {
    a: function(node, data) {
      data.a = true;
      return console.dir(data);
    },
    b: function(node, data) {
      if (data.b != null) {
        throw 'flow-stop';
      }
      return data.b = true;
    },
    c: function(node, data) {
      return data.c = true;
    }
  };

  jflow.run(json, {
    foo: "bar"
  }, {
    root: 'b',
    process: process
  });

  jflow.run(json, {
    foo: "bar"
  }, {
    root: 'd',
    process: process
  });

}).call(this);
