// Generated by CoffeeScript 1.9.3
(function() {
  var graph, jg, json;

  jg = require('jsongraph');

  json = {
    graph: {
      a: {
        "$ref": [
          {
            "$ref": "#/graph/b"
          }
        ]
      },
      b: {
        "$ref": [
          {
            "$ref": "#/graph/a"
          }
        ]
      },
      c: {
        "$ref": [
          {
            "$ref": "#/graph/a"
          }
        ]
      }
    }
  };

  jg.opts.verbose = 2;

  graph = jg.init(json);

  graph.run('b', {
    foo: "bar"
  });

}).call(this);
