// Generated by CoffeeScript 1.9.3
(function() {
  var jflow, json, process;

  jflow = require('jsonflow');

  json = {
    a: {
      output: [
        {
          "$ref": "#/b"
        }
      ]
    },
    b: {
      output: [
        {
          "$ref": "#/a"
        }
      ]
    },
    c: {
      output: [
        {
          "$ref": "#/a"
        }
      ]
    },
    d: {
      output: [
        {
          "$ref": "#/c"
        }
      ]
    }
  };

  process = {
    a: function(me, data, next) {
      data.a = true;
      console.dir(data);
      return next(me, data);
    },
    b: function(me, data, next) {
      if (data.b != null) {
        throw 'flow-stop';
      }
      data.b = true;
      return next(me, data);
    },
    c: function(me, data, next) {
      data.c = true;
      return next(me, data);
    }
  };

  jflow.run(json, {
    foo: "bar"
  }, {
    root: 'b',
    process: process
  });

  jflow.run(json, {
    foo: "bar"
  }, {
    root: 'd',
    process: process
  });

}).call(this);
